// ./js/brands.seed.js
// (Sadece veri) Seed marka listeleri burada. app.js içinden kaldırıldı.

export const AIDE_BRAND_SEED = [
  "ABLETON",
  "ADAM",
  "AKAI",
  "AKÇELİK",
  "AKG",
  "ALPHATHETA",
  "APPLE",
  "ART",
  "ARTURIA",
  "ASIMETRIKPRO",
  "ASTONMICROPHONES",
  "AUDIENT",
  "AUDIO TECHNICA",
  "B&W",
  "BEHRINGER",
  "BEYER",
  "BEYERDYNAMIC",
  "BİOLİTE",
  "BO",
  "BOSE PRO",
  "BROS&COMPANY",
  "CAMELBAK",
  "CORSAIR",
  "CTT",
  "DECKSAVER",
  "DENON",
  "DIVOOM",
  "DJ TECHTOOLS",
  "D-VOİCE",
  "EARTHWORKS",
  "ECLER",
  "EIKON",
  "ENOVA",
  "ERALP",
  "ESI AUDIO",
  "EUROCLUB",
  "EVENTIDE AUDIO",
  "FENDER",
  "FLİGHT",
  "FOCAL",
  "FOCUSRİTE",
  "GARMİN",
  "GATOR",
  "GEÇİCİ",
  "GENELEC",
  "GOBY LABS",
  "GRAVITY",
  "GTRS",
  "HEADRUSH",
  "HİFİMAN",
  "HOSA",
  "IK MULTIMEDIA",
  "INSTAX",
  "JBL",
  "KANTON",
  "KIRLIN",
  "KLARKTEKNIK",
  "KORG",
  "KOSS",
  "KÖNIG & MEYER",
  "KRK",
  "LDSYSTEMS",
  "LENCO",
  "MACKIE",
  "MAONO",
  "MARK STRINGS",
  "M-AUDIO",
  "MAXON",
  "MODAL ELECTRONICS",
  "MOGAMİ",
  "MOONDROP",
  "MOTU",
  "NEDIS",
  "NEUMANN",
  "NOVATION",
  "NUMARK",
  "ONEODIO",
  "OXID",
  "OXOGEAR",
  "OYAIDE",
  "PALMER",
  "PATONA",
  "PEAK DESIGN",
  "PIONEER",
  "PRESONUS",
  "RCF",
  "RELOOP",
  "RODE",
  "ROLAND",
  "RS AUDIO",
  "SE ELEKTRONICS",
  "SENNHEISER",
  "SESCİBABA",
  "SHURE",
  "SLATE",
  "SOUNDBOKS",
  "SSL",
  "STEINBERG",
  "STI",
  "SUDIO",
  "TAMA",
  "TANNOY",
  "TANTRUM",
  "TASCAM",
  "TC ELECTRONIC",
  "TC HELICON",
  "TEENAGE ENGINEERING",
  "TEKNIK",
  "TIE",
  "TOPPING AUDIO",
  "TRİTON",
  "TRUTHEAR",
  "UFUK ONEN",
  "ULTIMATE",
  "ULTİMATE",
  "UNIVERSAL",
  "WARMAUDIO",
  "WORLDE",
  "YAMAHA",
];

export const TSOFT_BRAND_SEED = [
  "Behringer",
  "Peak Design",
  "M-Audio",
  "Rode",
  "Ableton",
  "Nedis",
  "Arturia",
  "Rcf",
  "Universal Audio",
  "Marantz",
  "Numark",
  "Denon DJ",
  "Presonus",
  "Lindell Audio",
  "Access Music",
  "Genelec",
  "Audio Technica",
  "Rane",
  "Avalon",
  "Crane Song",
  "Rupert Neve",
  "Native Instruments",
  "Steinberg",
  "Warm Audio",
  "Audient",
  "IsoAcoustics",
  "Mxl",
  "ADAM Audio",
  "ESI Audio",
  "Radial Engineering",
  "IK Multimedia",
  "Focusrite",
  "Novation",
  "Mackie",
  "Nektar",
  "Apogee",
  "Yamaha",
  "Turbosound",
  "Nord",
  "sE Electronics",
  "Sennheiser",
  "Dynaudio",
  "Bowers & Wilkins",
  "Neumann",
  "Pioneer",
  "König & Meyer",
  "Hosa",
  "M&K Sound",
  "Audix",
  "Focal",
  "Alesis",
  "Boss",
  "Shure",
  "SesciBaba",
  "TC Electronic",
  "TC Helicon",
  "CTT",
  "Denon",
  "Inter",
  "Marshall",
  "I Light",
  "AKG",
  "CROWN",
  "JBL",
  "BSS",
  "Aston Microphones",
  "ENOVA",
  "KRK Systems",
  "KALI Audio",
  "HEADRUSH",
  "Neutrik",
  "Icon Pro Audio",
  "Joué",
  "AC Infinity",
  "Disan",
  "EVE AUDIO",
  "Acme",
  "Bosch",
  "Christie",
  "Impact",
  "ITC",
  "Arya",
  "ASY",
  "Cosmo",
  "ICA",
  "LD System",
  "Toa",
  "SonarWorks",
  "MOTU",
  "DPA Microphones",
  "MIDIPLUS",
  "RME",
  "SSL",
  "Modal Electronics",
  "Martin Audio",
  "Slate Digital",
  "Stanton",
  "Reloop",
  "Lab Gruppen",
  "Worlde",
  "Beyerdynamic",
  "Audeze",
  "Cranborne Audio",
  "Tie Products",
  "SoundSwitch",
  "Maono",
  "AKAI",
  "KORG",
  "Steven Slate Audio",
  "M-Game",
  "SOUNDBOKS",
  "Monster Cable",
  "NEO",
  "OneOdio",
  "Polyend",
  "Sudio",
  "Mogami",
  "AVMATRIX",
  "Nedis Cable",
  "Gator Frameworks",
  "Reloop HiFi",
  "PeakDesign",
  "Truthear",
  "Decksaver",
  "Procase",
  "AlphaTheta",
  "Maxon",
  "Antelope Audio",
  "Sheeran Loopers",
  "Yellowtec",
  "4THEWALL",
  "Bose",
  "Ultimate Support",
  "Studiologic by Fatar",
  "Erica Synths",
  "Soma Synths",
  "Gravity",
  "Technics",
  "TECHNICS",
  "Polk Audio",
  "DALI Audio",
  "Relacart",
  "D&R Electronica",
  "Ecler",
  "Telefunken",
  "Harrison Audio",
  "Triton Audio",
  "LENCO",
  "KANTO",
  "D-Voice",
  "Allen Heath",
  "DJ TechTools",
  "Oxogear",
  "Lake People",
  "Topping Professional",
  "Palmer",
  "LD Systems",
  "EIKON",
  "Moondrop",
  "VOX",
  "Sequenz",
  "WAGON",
  "SAKAE",
  "Doto Design",
  "Neo Created by OYAIDE Elec.",
  "Eventide Audio",
  "Barefoot",
  "Eve Audio",
  "PSI Audio",
  "Tantrum Audio",
  "ATC Loudspeakers",
  "Topping Audio",
  "Teenage Engineering",
  "Koss",
  "Hifiman",
  "Phase",
  "Odisei Music",
  "MXL Microphones",
  "Signex",
  "Drawmer",
  "Midiplus",
  "Auratone",
  "Sivga Audio",
  "Sendy Audio",
  "Earthworks Audio",
  "Telefunken Elektroakustik",
  "Steven Slate | Audio",
  "Embodme",
  "CEntrance",
  "Freqport",
  "Evo By Audient",
  "Monster Audio",
  "Rhodes",
  "High Line",
  "Fender Studio",
  "Corsair",
];
